/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Guilherme
 */
public class Calculator extends javax.swing.JFrame {
    String display = " ";
    String text;
    double firstOperand;
    double secondOperand;
    double res;
    double fo;
    int opI;

    /**
     * Creates new form Calc
     */
    public Calculator() {
        initComponents();
    }
    
    public void refreshDisplay(String text){
        textShow.setText(text);
    }
    
    public double getFirstOp(){
        firstOperand = Double.parseDouble(display);
        display = " ";
        refreshDisplay(display);
        return firstOperand;
    }
    
    public String add(double fOpr, double SOpr){
        
        res = fOpr + SOpr;
        text = Double.toString(res);
        return text;
    }
    
    public String sub(double fOpr, double SOpr){
        res = fOpr - SOpr;
        text = Double.toString(res);
        return text;
    }
    
    public String mult(double fOpr, double SOpr){
        res = fOpr * SOpr;
        text = Double.toString(res);
        return text;
    }
    
    public String div(double fOpr, double SOpr){
        res = fOpr / SOpr;
        text = Double.toString(res);
        return text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        press7 = new javax.swing.JButton();
        press8 = new javax.swing.JButton();
        press9 = new javax.swing.JButton();
        press4 = new javax.swing.JButton();
        press5 = new javax.swing.JButton();
        press6 = new javax.swing.JButton();
        press1 = new javax.swing.JButton();
        press2 = new javax.swing.JButton();
        press3 = new javax.swing.JButton();
        press0 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        plusOp = new javax.swing.JButton();
        lessOp = new javax.swing.JButton();
        multOp = new javax.swing.JButton();
        divOp = new javax.swing.JButton();
        cleanOp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textShow = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        press7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press7.setText("7");
        press7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press7ActionPerformed(evt);
            }
        });

        press8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press8.setText("8");
        press8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press8ActionPerformed(evt);
            }
        });

        press9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press9.setText("9");
        press9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press9ActionPerformed(evt);
            }
        });

        press4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press4.setText("4");
        press4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press4ActionPerformed(evt);
            }
        });

        press5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press5.setText("5");
        press5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press5ActionPerformed(evt);
            }
        });

        press6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press6.setText("6");
        press6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press6ActionPerformed(evt);
            }
        });

        press1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press1.setText("1");
        press1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press1ActionPerformed(evt);
            }
        });

        press2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press2.setText("2");
        press2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press2ActionPerformed(evt);
            }
        });

        press3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press3.setText("3");
        press3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press3ActionPerformed(evt);
            }
        });

        press0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        press0.setText("0");
        press0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                press0ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton11.setText("=");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        plusOp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        plusOp.setText("+");
        plusOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusOpActionPerformed(evt);
            }
        });

        lessOp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lessOp.setText("-");
        lessOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessOpActionPerformed(evt);
            }
        });

        multOp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        multOp.setText("X");
        multOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multOpActionPerformed(evt);
            }
        });

        divOp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        divOp.setText("/");
        divOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divOpActionPerformed(evt);
            }
        });

        cleanOp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cleanOp.setText("CE");
        cleanOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanOpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Calculadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textShow, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(press7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(press8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(press9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(press4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(press5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(press6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(press0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(press1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(press2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(press3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cleanOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(divOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plusOp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lessOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(textShow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divOp)
                    .addComponent(cleanOp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(press7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(press8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(press9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(multOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(press4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(press5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(press6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lessOp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(press1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(press2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(press3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(press0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(plusOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void press1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press1ActionPerformed
        // TODO add your handling code here:
        display = display.concat("1");
        refreshDisplay(display);
    }//GEN-LAST:event_press1ActionPerformed

    private void press0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press0ActionPerformed
        // TODO add your handling code here:
        display = display.concat("0");
        refreshDisplay(display);
    }//GEN-LAST:event_press0ActionPerformed

    private void press2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press2ActionPerformed
        // TODO add your handling code here:
        display = display.concat("2");
        refreshDisplay(display);
    }//GEN-LAST:event_press2ActionPerformed

    private void press3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press3ActionPerformed
        // TODO add your handling code here:
        display = display.concat("3");
        refreshDisplay(display);
    }//GEN-LAST:event_press3ActionPerformed

    private void press4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press4ActionPerformed
        // TODO add your handling code here:
        display = display.concat("4");
        refreshDisplay(display);
    }//GEN-LAST:event_press4ActionPerformed

    private void press5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press5ActionPerformed
        // TODO add your handling code here:
        display = display.concat("5");
        refreshDisplay(display);
    }//GEN-LAST:event_press5ActionPerformed

    private void press6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press6ActionPerformed
        // TODO add your handling code here:
        display = display.concat("6");
        refreshDisplay(display);
    }//GEN-LAST:event_press6ActionPerformed

    private void press7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press7ActionPerformed
        // TODO add your handling code here:
        display = display.concat("7");
        refreshDisplay(display);
    }//GEN-LAST:event_press7ActionPerformed

    private void press8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press8ActionPerformed
        // TODO add your handling code here:
        display = display.concat("8");
        refreshDisplay(display);
    }//GEN-LAST:event_press8ActionPerformed

    private void press9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_press9ActionPerformed
        // TODO add your handling code here:
        display = display.concat("9");
        refreshDisplay(display);
    }//GEN-LAST:event_press9ActionPerformed

    private void cleanOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanOpActionPerformed
        // TODO add your handling code here:
        display = " ";
        refreshDisplay(display);
    }//GEN-LAST:event_cleanOpActionPerformed

    private void plusOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusOpActionPerformed
        // TODO add your handling code here:
        fo = getFirstOp();
        opI = 1;
        
    }//GEN-LAST:event_plusOpActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        secondOperand = Double.parseDouble(textShow.getText());
        double so = secondOperand;
       if(opI == 1){
            String res = add(fo, so);
            refreshDisplay(res);
            refreshDisplay(text);
       }
       
       else if(opI == 2){
            String res = sub(fo, so);
            refreshDisplay(res);
            refreshDisplay(text);
       }
       
       else if(opI == 3){
            String res = mult(fo, so);
            refreshDisplay(res);
            refreshDisplay(text);
       }
       
       else if(opI == 4){
            String res = div(fo, so);
            refreshDisplay(res);
            refreshDisplay(text);
       }
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void lessOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessOpActionPerformed
        // TODO add your handling code here:
        fo = getFirstOp();
        opI = 2;
    }//GEN-LAST:event_lessOpActionPerformed

    private void multOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multOpActionPerformed
        // TODO add your handling code here:
        fo = getFirstOp();
        opI = 3;
    }//GEN-LAST:event_multOpActionPerformed

    private void divOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divOpActionPerformed
        // TODO add your handling code here:
        fo = getFirstOp();
        opI = 4;
    }//GEN-LAST:event_divOpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanOp;
    private javax.swing.JButton divOp;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lessOp;
    private javax.swing.JButton multOp;
    private javax.swing.JButton plusOp;
    private javax.swing.JButton press0;
    private javax.swing.JButton press1;
    private javax.swing.JButton press2;
    private javax.swing.JButton press3;
    private javax.swing.JButton press4;
    private javax.swing.JButton press5;
    private javax.swing.JButton press6;
    private javax.swing.JButton press7;
    private javax.swing.JButton press8;
    private javax.swing.JButton press9;
    private javax.swing.JTextField textShow;
    // End of variables declaration//GEN-END:variables
}
